language: cpp

cache:
 - apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libc6-i386 lib32stdc++6 lib32z1

env:
  global: 
    - TEST_NAME=""

before_script:
 - echo ${TEST_NAME}

matrix:
  include:
    - env:    TEST_NAME="gcc (host)"
      compiler: gcc
      language: cpp
      script:
        - make -s -j2 

    - env:    TEST_NAME="arm-linux-gnueabihf-gcc (target)"
      compiler: gcc
      language: cpp
      script:
        - curl http://downloads.ti.com/sitara_linux/esd/AM335xSDK/latest/exports/ti-sdk-am335x-evm-08.00.00.00-Linux-x86-Install.bin >ti-sdk-am335x-evm-08.00.00.00-Linux-x86-Install.bin
        - ./ti-sdk-am335x-evm-08.00.00.00-Linux-x86-Install.bin --mode unattended
        - make -s -j2 hosttools DEFAULT_TARGET=shared_release
        - export PATH=$PATH:`pwd`/linux-devkit/sysroots/i686-arago-linux/usr/bin; POCO_CONFIG=Arago make -s -j2 DEFAULT_TARGET=shared_release
